<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ai.Orchestrator.Plugins.Email\Ai.Orchestrator.Plugins.Email.csproj" />
    <ProjectReference Include="..\Ai.Orchestrator.Plugins.Memories\Ai.Orchestrator.Plugins.Memories.csproj" />
    <ProjectReference Include="..\Ai.Orchestrator.Plugins.OpenAi\Ai.Orchestrator.Plugins.OpenAi.csproj" />
    <ProjectReference Include="..\Ai.Orchestrator.Plugins.Webhook\Ai.Orchestrator.Plugins.Webhook.csproj" />
  </ItemGroup>

</Project>
